#!/usr/bin/env python3
"""Ultra-compact GitHub PDF Report Generator - Ephemeral Script (<3KB)"""
from datetime import datetime as dt
from jinja2 import Template as T
from weasyprint import HTML as H

H(string=T("""<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@page{size:A4;margin:2cm}*{margin:0;padding:0}body{font-family:'Segoe UI',sans-serif;color:#24292e}.h{border-bottom:3px solid #0366d6;padding:20px 0 20px 0;margin-bottom:30px}.h h1{color:#0366d6;font-size:28px}.h p{color:#586069;font-size:13px}.u{background:#f6f8fa;border-left:4px solid #0366d6;padding:15px;margin-bottom:30px}.u h2{color:#0366d6;font-size:15px;margin-bottom:8px}.u p{font-size:12px;color:#586069;margin:4px 0}.s{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-bottom:30px}.c{background:#f6f8fa;border:1px solid #e1e4e8;padding:15px;border-radius:6px;text-align:center}.c .n{font-size:24px;font-weight:bold;color:#0366d6}.c .l{font-size:11px;color:#586069;text-transform:uppercase}.t{color:#0366d6;font-size:18px;font-weight:600;margin:30px 0 15px 0;border-bottom:2px solid #e1e4e8;padding-bottom:10px}table{width:100%;border-collapse:collapse;margin-bottom:20px;font-size:12px}thead{background:#f6f8fa;border-bottom:2px solid #0366d6}th{padding:12px;text-align:left;font-weight:600;color:#0366d6}td{padding:12px;border-bottom:1px solid #e1e4e8}tbody tr:hover{background:#f6f8fa}.r{background:#f6f8fa;border:1px solid #e1e4e8;border-radius:6px;padding:15px;margin-bottom:15px}.r h3{color:#0366d6;font-size:14px;margin-bottom:8px}.r .m{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;font-size:11px;color:#586069}.r .m strong{color:#24292e;margin-right:5px}.f{margin-top:40px;padding-top:15px;border-top:1px solid #e1e4e8;text-align:center;font-size:10px;color:#6a737d}</style></head><body>
<div class="h"><h1>📊 Informe de Repositorios GitHub</h1><p>{{ d }} | {{ n }} (@{{ l }})</p></div>
<div class="u"><h2>👤 Usuario</h2><p><strong>Nombre:</strong> {{ n }}</p><p><strong>Login:</strong> @{{ l }}</p></div>
<div class="s"><div class="c"><div class="n">{{ p }}</div><div class="l">Públicos</div></div><div class="c"><div class="n">{{ v }}</div><div class="l">Privados</div></div><div class="c"><div class="n">{{ z }}</div><div class="l">Tamaño</div></div></div>
<h2 class="t">📦 Resumen</h2>
<table><thead><tr><th>Nombre</th><th>Lenguaje</th><th>⭐</th><th>Actualizado</th></tr></thead><tbody>{% for r in rs %}<tr><td><strong>{{ r.n }}</strong></td><td>{{ r.g }}</td><td>{{ r.s }}</td><td>{{ r.u }}</td></tr>{% endfor %}</tbody></table>
<h2 class="t">🔍 Detalles</h2>
{% for r in rs %}<div class="r"><h3>{{ r.n }}</h3><div class="m"><div><strong>Lenguaje:</strong> {{ r.g }}</div><div><strong>Estrellas:</strong> {{ r.s }}</div><div><strong>Actualizado:</strong> {{ r.u }}</div><div><strong>URL:</strong> <a href="{{ r.w }}">GitHub</a></div></div></div>{% endfor %}
<div class="f"><p>Generado automáticamente | GitHub Report Generator</p></div>
</body></html>""").render(d=dt.now().strftime("%d %b %Y"),n="Gloria Peralta",l="gloriaperaltav",p=2,v=0,z="3.7 KB",rs=[{"n":"qa_cypress_orion","g":"TypeScript","s":0,"u":"12 Mar 2025","w":"https://github.com/gloriaperaltav/qa_cypress_orion"},{"n":"TEST","g":"—","s":0,"u":"4 Sep 2026","w":"https://github.com/gloriaperaltav/TEST"}])).write_pdf("repositorios_github.pdf");print("✅ PDF generado: repositorios_github.pdf")
